version: '3.8'
services:
  ai-agent-service:
    container_name: ai-agent-service
    build: ./ai-agent-service/
    image: ai-agent-service:latest
    ports:
      - "8000:8000"
    volumes:
      - ./ai-agent-service:/app
    env_file:
      - .env

    
