version: '3.8'
services:
  prompt-engineering-api:
    container_name: prompt-engineering-api
    build: .
    image: prompt-engineering-api:latest
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    env_file:
      - .env

    
